version: "2"
services:
    postgres:
        image: postgres:14.18
        container_name: postgres
        restart: always
        ports:
            - "15432:5432"
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=0d00pwd
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ./postgresql/data:/var/lib/postgresql/data
    odoo:
        image: odoo:18.0
        container_name: odoo
        restart: always
        ports:
            - "18069:8069"
            - "18072:8072"
        environment:
            - HOST=postgres
            - PORT=5432
            - USER=odoo
            - PASSWORD=0d00pwd
        volumes:
            - ./odoo/addons:/mnt/extra-addons
            - ./odoo/config:/etc/odoo
            - ./odoo/log:/var/log/odoo
            - ./odoo/data:/var/lib/odoo
        depends_on:
            - postgres
